fix(graphql): Broken upstream API fix [DEV-1726]
cheqd/data-api pull request #22
Opened 2022-09-13 23:37 UTC by ankurdotb

2022-09-14 09:10 UTC, drgomesp submitted a review, later dismissed
Looks good!

2022-09-28 23:01 UTC, ankurdotb commented on src/handlers/circulatingSupply.ts
> +        console.log(`Non-circulating supply: ${non_circulating_supply_ncheq}`);
I get the sense that the formula used for calculating circulating supply isn't exactly the same. The new formula seems to only account for total balance. Am I right?

2022-09-29 09:08 UTC, drgomesp commented on src/handlers/circulatingSupply.ts
> +        })
This endpoint is not processing the balances or the calculation, but rather only fetching the updated balances and returning the sum. However, this endoint is now quite slow due to the changes we made, which is why I suggested previously we should also cache the total circulating supply in every cron execution so that we can fetch it fast from the endpoint. That's what I'm going to do once all the calculations are confirmed to be fine.

2022-09-29 09:10 UTC, drgomesp commented on src/handlers/circulatingSupply.ts
> +        console.log(`Non-circulating supply: ${non_circulating_supply_ncheq}`);
If you are referring to the fact that we were considering delayed accounts previously as well, I believe I asked you about this and you said the new query should take care of all accounts, and therefore the circulating supply calculation gets simpler. Unless it's about something else?

2022-09-29 16:05 UTC, askolesov commented on src/helpers/graphql.ts
> +            return {} as T;
The same

2022-09-29 17:27 UTC, askolesov commented on src/index.ts
> +})
Looks like they are executed in parallel because the function is not async.

2022-09-30 06:20 UTC, askolesov commented on src/handlers/cron.ts
> +export async function updateAllBalances(group: number, event: Event) {
Can we move this to 'handler/balanceUpdater' or 'helpers/balance'? As I can see this is called not by cron only.

2022-09-30 06:20 UTC, askolesov commented on src/handlers/cron.ts
> +        console.error(e)
Why not rethrow?

2022-09-30 06:20 UTC, askolesov commented on src/handlers/cron.ts
> +        console.error(e)
Also I would call it 'updateGroupBalances'

2022-09-30 06:24 UTC, askolesov commented on src/handlers/cron.ts
> +                if (key.name.startsWith("grp_")) {
Why do we check that key starts with 'grp_' after querying all keys with this prefix?

2022-09-30 06:28 UTC, ankurdotb commented on src/handlers/cron.ts
> +                if (key.name.startsWith("grp_")) {
Agree, if you fetch without prefix it will fetch all (as long as the KV has been cleaned up for unique values)

2022-09-30 06:28 UTC, ankurdotb commented on src/handlers/cron.ts
> +                if (key.name.startsWith("grp_")) {
At the moment this is a hack because non prefixed data also exists in the KV but this is easily fixed

2022-09-30 06:31 UTC, askolesov commented on src/helpers/balance.ts
> +export async function updateBalance(node_api: NodeApi, addr: string, grpN: number): Promise<Response> {
Why does upddate function return 'Response' object?

2022-09-30 06:31 UTC, askolesov commented on src/helpers/balance.ts
> +            console.log(`account "${addr}" balance updated. (res=${JSON.stringify(account)})`)
Why does it update cache only when account is already in cache?

2022-09-30 06:33 UTC, askolesov commented on src/helpers/balance.ts
> +export async function updateBalance(node_api: NodeApi, addr: string, grpN: number): Promise<Response> {
It's much better to return 'int' or 'Account' object and throw in case of error.

2022-09-30 06:34 UTC, askolesov commented on src/helpers/balance.ts
> +export async function updateBalance(node_api: NodeApi, addr: string, grpN: number): Promise<Response> {
Again, from what I see better name is 'updateCachedBalance' or 'updateBalanceCache'.

2022-09-30 06:37 UTC, askolesov commented on src/handlers/cron.ts
> +                    const data = await res.json() as Account;
Just make 'updateBalanse' to return 'Acccount' instead of packing/unpacking into Response.

2022-09-30 06:39 UTC, askolesov commented on src/handlers/cron.ts
> +        return new Response(JSON.stringify(balances));
Again, don't return 'Response' in methods that are not handlers.

2022-09-30 06:39 UTC, askolesov commented on src/handlers/cron.ts
> +export async function updateAllBalances(group: number, event: Event) {
Why not rethrow?

2022-09-30 06:41 UTC, askolesov commented on src/handlers/balanceUpdater.ts
> +    const grp = request.params?.['grp'];
It's better to make sure that group is not null begfore processing.

2022-09-30 06:46 UTC, askolesov commented on src/index.ts
> +})
Let's not hardcode the number of groups and move it to configuration instead.

2022-09-30 06:53 UTC, askolesov commented on src/handlers/circulatingSupply.ts
> +    let addresses_to_exclude: string[] = (await CIRCULATING_SUPPLY_WATCHLIST.list()).keys.filter(k => !k.name.startsWith("grp_"));
We load all the keys in lambda's memory here. It's not safe.

2022-09-30 06:56 UTC, askolesov commented on src/handlers/circulatingSupply.ts
> +    let addresses_to_exclude: string[] = (await CIRCULATING_SUPPLY_WATCHLIST.list()).keys.filter(k => !k.name.startsWith("grp_"));
! And the most interesting part is that those addresses are not used at all.

2022-09-30 06:59 UTC, askolesov commented on src/handlers/circulatingSupply.ts
> +        const cached = await CIRCULATING_SUPPLY_WATCHLIST.list({
Again, we iterate throug all accounts every request. We can get out of kv reads really soon. I would cache group balances and iterate only them here.

2022-09-30 06:59 UTC, askolesov commented on src/handlers/circulatingSupply.ts
> +    let addresses_to_exclude: string[] = (await CIRCULATING_SUPPLY_WATCHLIST.list()).keys.filter(k => !k.name.startsWith("grp_"));
So let's get rid of this?

2022-09-30 07:40 UTC, askolesov requested changes
Ok, so that's what I see:
* We have a list of accounts to exclude;
* Cron job updates their balances;
* Circulating supply endpoint queries total supply and subtracts cached balances from it.

Everything looks reasonable. Improvement suggestions from my side:
* Cache group balances and iterate them instead of iterating all accounts
* Improve error handling and overall code quality

Looks good overall. Thanks!

2022-09-30 07:46 UTC, askolesov commented on src/handlers/cron.ts
> +export async function updateAllBalances(group: number, event: Event) {
Also I would call it 'updateGroupBalances'

2022-09-30 10:07 UTC, drgomesp commented on src/helpers/balance.ts
> +            console.log(`account "${addr}" balance updated. (res=${JSON.stringify(account)})`)
This was like a "defense" mechanism due to having more entries present in the KV that were being used for other things. I have cleaned it up now and will adjust the code for that too.

2022-10-11 09:01 UTC, benyam7 commented on src/handlers/totalBalance.ts
> +    if (is_delayed_vesting_account_type(auth_account?.["@type"])) {
it works

2022-10-11 11:00 UTC, benyam7 commented on src/handlers/totalBalance.ts
> +    if (is_delayed_vesting_account_type(auth_account?.["@type"])) {
well, we cannot say it works because when I cross check the result on explorer.cheqd.io it is different.

2022-10-14 19:01 UTC, merged

2025-03-13 12:36 UTC, ankurdotb commented
Task linked: [DEV-1726 Fix broken API for custom data API](https://app.clickup.com/t/6600954/DEV-1726)